# Code generated by volt — DO NOT EDIT.
# Regenerate by releasing browserctrl; edits here are overwritten on the next release.
class Browserctrl < Formula
  desc "Map Claude-in-Chrome device ids to the Chromium browser, profile and email behind them"
  homepage "https://github.com/khanakia/browserctrl"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/khanakia/browserctrl/releases/download/v0.1.0/browserctrl_v0.1.0_darwin_arm64.tar.gz"
      sha256 "bb0bbc9faeb8bf31922044c0a35a0aa35fde2b93342cc5c703190dab5ab9abf1"
    end
    on_intel do
      url "https://github.com/khanakia/browserctrl/releases/download/v0.1.0/browserctrl_v0.1.0_darwin_amd64.tar.gz"
      sha256 "e2a4e1b654d2040d780d837862350cd667808cec2c4aed8d0f4c75ba74145162"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/khanakia/browserctrl/releases/download/v0.1.0/browserctrl_v0.1.0_linux_arm64.tar.gz"
      sha256 "606137a614819ead9f1f4d6e317c915f766c4440f696c80709373dd6b75e6d7b"
    end
    on_intel do
      url "https://github.com/khanakia/browserctrl/releases/download/v0.1.0/browserctrl_v0.1.0_linux_amd64.tar.gz"
      sha256 "915793eff2557f68024b21261a473112b4e1ee54b0c30546c697302ac8b54843"
    end
  end

  def install
    bin.install "browserctrl"
  end

  test do
    system "#{bin}/browserctrl", "--version"
  end
end
