# Code generated by volt — DO NOT EDIT.
# Regenerate by releasing browserctrl; edits here are overwritten on the next release.
class Browserctrl < Formula
  desc "Map Claude-in-Chrome device ids to the Chromium browser, profile and email behind them"
  homepage "https://github.com/khanakia/browserctrl"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/khanakia/browserctrl/releases/download/v0.1.1/browserctrl_v0.1.1_darwin_arm64.tar.gz"
      sha256 "44b452093b1ca6db83ce3a0e6f864dec65076d786b7177259013f9e606b14abf"
    end
    on_intel do
      url "https://github.com/khanakia/browserctrl/releases/download/v0.1.1/browserctrl_v0.1.1_darwin_amd64.tar.gz"
      sha256 "852d8a5ee09abfb2b35185d6c960e42f448db5e5a05f72a0866690fb08295f93"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/khanakia/browserctrl/releases/download/v0.1.1/browserctrl_v0.1.1_linux_arm64.tar.gz"
      sha256 "c025ff2c167245617cd06acf0ab96fda10e113e6a5ea8da4d2a6c2f2514f2bc0"
    end
    on_intel do
      url "https://github.com/khanakia/browserctrl/releases/download/v0.1.1/browserctrl_v0.1.1_linux_amd64.tar.gz"
      sha256 "b34167cc617606274cd4f74d64cf39800cdc07d053e442b1e9057abf38c603e1"
    end
  end

  def install
    bin.install "browserctrl"
  end

  test do
    system "#{bin}/browserctrl", "--version"
  end
end
