# Code generated by volt — DO NOT EDIT.
# Regenerate by releasing volt; edits here are overwritten on the next release.
class Volt < Formula
  desc "Build, release and ship Go CLIs and libraries — any repo layout, one command"
  homepage "https://github.com/khanakia/voltkit"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/khanakia/voltkit/releases/download/volt/v0.1.0/volt_v0.1.0_darwin_arm64.tar.gz"
      sha256 "86f9f4551ab9f20916fb163b4e6bed15d06bf6c5352c3b77b881ee319deeba5c"
    end
    on_intel do
      url "https://github.com/khanakia/voltkit/releases/download/volt/v0.1.0/volt_v0.1.0_darwin_amd64.tar.gz"
      sha256 "638ffeecc3c41b9f01985047dd57185b187118e7f3fce51044eaa99c291a68a7"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/khanakia/voltkit/releases/download/volt/v0.1.0/volt_v0.1.0_linux_arm64.tar.gz"
      sha256 "6f6d9c1cc34307dd0fbf143713772d1a56d86934a22a26d57cb2b619c93e8918"
    end
    on_intel do
      url "https://github.com/khanakia/voltkit/releases/download/volt/v0.1.0/volt_v0.1.0_linux_amd64.tar.gz"
      sha256 "98ee2ee7271a38ec2e17a58d6edb4d5d18df4be94921967c750e0d93fe990439"
    end
  end

  def install
    bin.install "volt"
  end

  test do
    system "#{bin}/volt", "--version"
  end
end
