# Code generated by volt — DO NOT EDIT.
# Regenerate by releasing volt; edits here are overwritten on the next release.
class Volt < Formula
  desc "Build, release and ship Go CLIs and libraries — any repo layout, one command"
  homepage "https://github.com/khanakia/voltkit"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/khanakia/voltkit/releases/download/volt/v0.3.0/volt_v0.3.0_darwin_arm64.tar.gz"
      sha256 "571dcf61463e785a2f3b641f72d09c2a9f2f0ea93244ec08e30c7e88edc61c4a"
    end
    on_intel do
      url "https://github.com/khanakia/voltkit/releases/download/volt/v0.3.0/volt_v0.3.0_darwin_amd64.tar.gz"
      sha256 "f829d9ba04691cb6c7409d55f6ad40b2a3dd0b491720fb544cf1ff61a3be67e5"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/khanakia/voltkit/releases/download/volt/v0.3.0/volt_v0.3.0_linux_arm64.tar.gz"
      sha256 "7278968e32ac2f67ca09abe3a3d22a140c55ee9a521c6a066313f649123ef344"
    end
    on_intel do
      url "https://github.com/khanakia/voltkit/releases/download/volt/v0.3.0/volt_v0.3.0_linux_amd64.tar.gz"
      sha256 "04b19a169f6b5a5d4d025be1fecd78406ec998f6e4c02320e259c88e06cf6475"
    end
  end

  def install
    bin.install "volt"
  end

  test do
    system "#{bin}/volt", "--version"
  end
end
