# Code generated by volt — DO NOT EDIT.
# Regenerate by releasing volt; edits here are overwritten on the next release.
class Volt < Formula
  desc "Build, release and ship Go CLIs and libraries — any repo layout, one command"
  homepage "https://github.com/khanakia/voltkit"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/khanakia/voltkit/releases/download/volt/v0.2.0/volt_v0.2.0_darwin_arm64.tar.gz"
      sha256 "355ffd7063a1e753bd48018479460f5ce03edcb54b1d8511db2170a0d16fc7e0"
    end
    on_intel do
      url "https://github.com/khanakia/voltkit/releases/download/volt/v0.2.0/volt_v0.2.0_darwin_amd64.tar.gz"
      sha256 "dfd57b1b94c96fac9eebf6a6569ea60dd47efac6b6c385f53557e1499b2f7619"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/khanakia/voltkit/releases/download/volt/v0.2.0/volt_v0.2.0_linux_arm64.tar.gz"
      sha256 "1a08629a2ccd5e06fbe7293e4540bb4cd223f30d0b0eeb579245a4374a95270b"
    end
    on_intel do
      url "https://github.com/khanakia/voltkit/releases/download/volt/v0.2.0/volt_v0.2.0_linux_amd64.tar.gz"
      sha256 "8c387159703322700d101933d688b26f92572ba8d132b811d55d23ebde0ef024"
    end
  end

  def install
    bin.install "volt"
  end

  test do
    system "#{bin}/volt", "--version"
  end
end
